name: Build and Release

on:
  push:
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # 获取完整的git历史，以便获取提交信息

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet publish -c Release -r win-x64 --self-contained false /p:PublishSingleFile=true /p:PublishReadyToRun=false

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Get commit message
      id: commit_message
      run: |
        $tag_name = "${{ github.ref_name }}"
        $commit_message = git log -1 --format=%B $tag_name
        $commit_message = $commit_message -replace "`n", "%0A"
        echo "message=$commit_message" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Zip Release Files
      run: |
        Compress-Archive -Path "bin\Release\net7.0-windows\win-x64\publish\*" -DestinationPath "AruScreenSummary_${{ steps.date.outputs.date }}_${{ github.ref_name }}.zip"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AruScreenSummary_${{ steps.date.outputs.date }}_${{ github.ref_name }}.zip
        name: Release ${{ github.ref_name }} (${{ steps.date.outputs.date }})
        body: |
          Release ${{ github.ref_name }}

          发布时间：${{ steps.date.outputs.date }}

          ## 更新内容
          ${{ steps.commit_message.outputs.message }}

          ## 运行环境要求
          - Windows 10/11
          - [.NET 7.0 Desktop Runtime](https://dotnet.microsoft.com/download/dotnet/7.0)

        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
